[package]
name = "turboani"
version = "0.1.8"
edition = "2024"
default-run = "turboani"
repository = "https://github.com/jianshu93/TurboANI.git"
license = "MIT"
description = "Super-fast ANI estimation with SIMD minimizers, efficient candidate window screening and bitset rolling bottom-s sketch order statistics over winnowed minimizers"
keywords = ["ANI", "minimizers", "mapping", "MinHash", "alignment"]

[features]
default = []
visual = ["dep:plotters", "dep:rammap-core", "dep:svg2pdf"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
needletail = "0.7.3"
flate2 = { version = "1.1.9", features = ["zlib-rs"], default-features = false }
plotters = { version = "0.3.7", optional = true }
rammap-core = { version = "1.1.2", default-features = false, features = ["parallel"], optional = true }
rayon = "1.11"
simd-minimizers = "3.0.0"
svg2pdf = { version = "0.13.0", optional = true }
tab-hash = "0.4.0"
num_cpus = "1"
env_logger = "0.11"
indicatif = "0.17"
log = "0.4"
murmur3 = "0.5.2"

[dev-dependencies]
tempfile = "3.23"

[[bin]]
name = "turboani"
path = "src/bin/turboani.rs"

[[bin]]
name = "fastani"
path = "src/bin/fastani.rs"

[[bin]]
name = "plot-correlation"
path = "src/bin/plot-correlation.rs"
required-features = ["visual"]

[[bin]]
name = "turboani-order"
path = "src/bin/turboani-order.rs"
required-features = ["visual"]
