[package]
name = "turboani"
version = "0.1.4"
edition = "2024"
default-run = "turboani"
repository = "https://github.com/jianshu93/TurboANI.git"
license = "MIT"
description = "Super-fast ANI estimation with SIMD minimizers, efficient candidate window screening and bitset rolling bottom-s sketch order statistics over winnowed minimizers"
keywords = ["ANI", "minimizers", "mapping", "MinHash", "alignment"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
needletail = "0.7.3"
plotters = "0.3.7"
rayon = "1.11"
simd-minimizers = "3.0.0"
svg2pdf = "0.13.0"
tab-hash = "0.3.0"
num_cpus = "1"
env_logger = "0.11"
log = "0.4"

[dev-dependencies]
tempfile = "3.23"

[[bin]]
name = "turboani"
path = "src/bin/turboani.rs"
